prompts:
    basic-prompt:
    - "Provide a brief explanation of {text} and list its three main components."
    - "What's the largest planet in {text}?"
    - "What is the capital of {text}?"

    zero-shot-prompt:
    - "Generate a short news article about {topic}. Structure your response in the following format: Headline: [ A catchy headline for the article ] Lead: [ A brief introductory paragraph summarizing the key points ] Body: [ 2-3 short paragraphs providing more details ] Conclusion: [ A concluding sentence or call to action ]"
    - "Analyze the following text for its main argument, supporting evidence, and potential counterarguments. Provide your analysis in the following steps: 1. Main Argument: Identify and state the primary claim or thesis. 2. Supporting Evidence: List the key points or evidence used to support the main argument. 3. Potential Counterarguments: Suggest possible objections or alternative viewpoints to the main argument. Text: { text } Analysis:"
    - "Explain {task} by addressing the following points: 1. Definition 2. Key features 3. Real-world applications 4. Potential impact on industries"

    few-shot-prompt:
    - "Classify the sentiment as Positive, Negative, or Neutral. Examples: Text: I love this product! It's amazing. Sentiment: Positive Text: This movie was terrible. I hated it. Sentiment: Negative Text: The weather today is okay. Sentiment: Neutral Now, classify the following: Text: {input_text} Sentiment:"
    - "Perform the specified task on the given text. Examples: Text: I love this product! It's amazing. Task: sentiment Result: Positive Text: Bonjour, comment allez-vous? Task: language Result: French Now, perform the following task: Text: {input_text} Task: {task} Result:"
    - "Task: {task_description} Examples: {examples} Now, perform the task on the following input: Input: {input_text} Output:"

    chain-of-thought-prompt:
    - "Solve the following problem step by step. For each step: 1. State what you're going to calculate 2. Write the formula you'll use (if applicable) 3. Perform the calculation 4. Explain the result Question: {question} Solution:"

    constrained-prompt:
    - "Create a product description for {product} targeted at {target_audience}. Use a {tone} tone and keep it under {word_limit} words. The description should include: 1. A catchy headline 2. Three key features 3. A call to action Product Description:"

    rule-based-prompt:
    - "Create a job posting for a {job_title} position at {company} in {location}. The candidate should have {experience} years of experience. Follow these rules: 1. Start with a brief company description (2 sentences) 2. List 5 key responsibilities, each starting with an action verb 3. List 5 required qualifications, each in a single sentence 4. End with a standardized equal opportunity statement Format the output as follows: COMPANY: [Company Description] RESPONSIBILITIES: [Responsibility 1] [Responsibility 2] [Responsibility 3] [Responsibility 4] [Responsibility 5] QUALIFICATIONS: [Qualification 1] [Qualification 2] [Qualification 3] [Qualification 4] [Qualification 5] EEO: [Equal Opportunity Statement]"

    role-based-prompt:
    - "You are a technical writer specializing in creating clear and concise documentation for software products. Your task is to write a brief explanation of {topic} for a user manual. Please provide a 2-3 sentence explanation that is easy for non-technical users to understand."
    - "You are a seasoned financial advisor with over 20 years of experience in personal finance, investment strategies, and retirement planning. You have a track record of helping clients from diverse backgrounds achieve their financial goals. Your approach is characterized by: 1. Thorough analysis of each client's unique financial situation 2. Clear and jargon-free communication of complex financial concepts 3. Ethical considerations in all recommendations 4. A focus on long-term financial health and stability Given the following client situation, provide a brief (3-4 sentences) financial advice: { client_situation } Your response should reflect your expertise and adhere to your characteristic approach."

    negative-prompt:
    - "Provide a brief explanation of {topic}. Do NOT include any of the following in your explanation: Technical jargon or complex terminology Historical background or dates Comparisons to other related topics Your explanation should be simple, direct, and focus only on the core concept."

    exclusion-prompt:
    - "Write a short paragraph about {topic}. Important: Do not mention or reference anything related to {exclude}."

#  TODO self-consistency-prompt:
#        - multiple-reasoning-prompt:
#            - "Solve the following problem using a unique approach. This is reasoning path {path_number}. Problem: {problem} Reasoning path {path_number}:"
#        - aggregating-prompt:
#            - "Analyze the following reasoning paths and determine the most consistent answer. If there are discrepancies, explain why and provide the most likely correct answer. Reasoning paths: {paths} Most consistent answer:"
#        - self-consistency-check:
#            - "Evaluate the consistency and reliability of the following result for the given problem. Problem: { problem } Result: { result } Evaluation (consider factors like logical consistency, adherence to known facts, and potential biases):"
#
#  TODO task-decomposition-prompt:
#        - decomposition-prompt:
#            - "Break down the task of analyzing a company's financial health into 3 subtasks. For each subtask, provide a brief description of what it should accomplish. Task: {task} Subtasks: 1."
#        - chaining-subtasks-prompt:
#            - "Based on the following analyses, provide an overall assessment of the company's financial health: Profitability Analysis: {profitability} Liquidity Analysis: {liquidity} Cash Flow Analysis: {cash_flow} Summarize the key points and give an overall evaluation of the company's financial position."
#            - "Analyze the company's liquidity based on the following data: Total Assets: ${total_assets} million Total Liabilities: ${total_liabilities} million Calculate the current ratio and provide a brief analysis of the company's liquidity."
#            - "Analyze the company's cash flow based on the following data: Cash Flow from Operations: ${cash_flow} million Provide a brief analysis of the company's cash flow health."
#        - result-integration-prompt:
#            - "Based on the following analyses, provide an overall assessment of the company's financial health: Profitability Analysis: {profitability} Liquidity Analysis: {liquidity} Cash Flow Analysis: {cash_flow} Summarize the key points and give an overall evaluation of the company's financial position."
#
#   TODO a-b-testing-prompt: []
#
#   TODO iterative-prompt: []
#
#   TODO ambiguity-clarity-prompt: []
