rags:
  - simple-rag
  - adaptive-rag
  - context-window-enhancement-rag
  - fusion-rag
  - graph-rag
  - semantic-chunking-rag
#  - TODO hyde-hypothetical-document-embedding-rag
#  - TODO hype-hypothetical-prompt-embeddings-rag
#  - TODO microsoft-graph-rag
#  - TODO choose-chunk-size-rag
#  - TODO contextual-chunk-headers-rag
#  - TODO contextual-compression-rag
#  - TODO crag
#  - TODO dartboard-rag
#  - TODO document-augmentation-rag
#  - TODO explainable-rag
#  - TODO hierarchical-indices-rag
#  - TODO multi-model-with-captioning-rag
#  - TODO multi-model-with-colpal-rag
#  - TODO proposition-chunking-rag
#  - TODO query-transformations-rag
#  - TODO raptor-rag
#  - TODO relevant-segment-extraction-rag
#  - TODO reliable-rag
#  - TODO reranking-rag
#  - TODO with-feedback-loop-rag
#  - TODO self-rag
#  - TODO simple-csv-rag
