rags:
  - simple-rag
  - adaptive-rag
  - context-window-enhancement-rag
  - fusion-rag
  - graph-rag
  - semantic-chunking-rag
# TODO
#  - hyde-hypothetical-document-embedding-rag
#  - hype-hypothetical-prompt-embeddings-rag
#  - microsoft-graph-rag
#  - choose-chunk-size-rag
#  - contextual-chunk-headers-rag
#  - contextual-compression-rag
#  - crag
#  - dartboard-rag
#  - document-augmentation-rag
#  - explainable-rag
#  - hierarchical-indices-rag
#  - multi-model-with-captioning-rag
#  - multi-model-with-colpal-rag
#  - proposition-chunking-rag
#  - query-transformations-rag
#  - raptor-rag
#  - relevant-segment-extraction-rag
#  - reliable-rag
#  - reranking-rag
#  - with-feedback-loop-rag
#  - self-rag
#  - simple-csv-rag
